fix: Change logo name to all lowercase
hidalest/dpiDriver-mobile pull request #5
Opened 2024-06-12 03:47 UTC by jurgen-alfaro

To fix this error: 
`> /home/expo/workingdir/build/android/app/src/main/res/drawable/companyLogo.png: Error: 'L' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore`

2024-06-12 20:47 UTC, hidalest requested changes
why there are changes in the package-lock.json and yarn.lock?

2024-06-13 01:20 UTC, jurgen-alfaro commented
> why there are changes in the package-lock.json and yarn.lock?

The changes in those two files are automatically made after running `npm install`.

2024-06-13 02:17 UTC, hidalest commented
good job

2024-06-13 02:18 UTC, hidalest approved these changes

2024-06-13 02:18 UTC, merged